### ISSUE TITLE
css calc is not supported

### ISSUE THREAD

**Issue by iflan** [google/closure-stylesheets#59]
Originally reported on Google Code with ID 40
```
What steps will reproduce the problem?

1. d:\Work\test>java -jar bin/closure-stylesheets.jar --rename CLOSURE --output-file
build/outputcompiled.css css/test.css

Contents of test.css:

.test{
   width: calc(100% - 1px);
}

What is the expected output? 

Expect to see minified css in file named outputcompiled.css 

What do you see instead?

Compiler parsing error: Parse error in css/test.css at line 2 column 22:
   width: calc(100% - 1px);
                     ^

com.google.common.css.compiler.ast.GssParserException: Parse error in css/test.css
at line 2 column 22:
   width: calc(100% - 1px);
                     ^

        at com.google.common.css.compiler.ast.GssParserCC.parse(GssParserCC.java:176)
        at com.google.common.css.compiler.ast.GssParser.parse(GssParser.java:46)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.parseAndPrint(DefaultCommandLineCompiler.ja
va:104)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.compile(DefaultCommandLineCompiler.java:94)

        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.execute(DefaultCommandLineCompiler.java:129
)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.executeJob(ClosureCommandLineCompiler.java:
290)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:356)
Caused by: com.google.common.css.compiler.ast.ParseException: Encountered " <S> " 
"" at line 2, column 22.
Was expecting:
    <NUMBER> ...

        at com.google.common.css.compiler.ast.GssParserCC.generateParseException(GssParserCC.java:3756)
        at com.google.common.css.compiler.ast.GssParserCC.jj_consume_token(GssParserCC.java:3635)
        at com.google.common.css.compiler.ast.GssParserCC.term(GssParserCC.java:1562)
        at com.google.common.css.compiler.ast.GssParserCC.slash_term(GssParserCC.java:1494)
        at com.google.common.css.compiler.ast.GssParserCC.assign_term(GssParserCC.java:1446)
        at com.google.common.css.compiler.ast.GssParserCC.composite_term(GssParserCC.java:1397)
        at com.google.common.css.compiler.ast.GssParserCC.expr(GssParserCC.java:1379)
        at com.google.common.css.compiler.ast.GssParserCC.function(GssParserCC.java:2092)
        at com.google.common.css.compiler.ast.GssParserCC.term(GssParserCC.java:1682)
        at com.google.common.css.compiler.ast.GssParserCC.slash_term(GssParserCC.java:1494)
        at com.google.common.css.compiler.ast.GssParserCC.assign_term(GssParserCC.java:1446)
        at com.google.common.css.compiler.ast.GssParserCC.composite_term(GssParserCC.java:1397)
        at com.google.common.css.compiler.ast.GssParserCC.expr(GssParserCC.java:1370)
        at com.google.common.css.compiler.ast.GssParserCC.standardDeclaration(GssParserCC.java:1335)
        at com.google.common.css.compiler.ast.GssParserCC.styleDeclaration(GssParserCC.java:1193)
        at com.google.common.css.compiler.ast.GssParserCC.ruleSet(GssParserCC.java:463)
        at com.google.common.css.compiler.ast.GssParserCC.block(GssParserCC.java:2856)
        at com.google.common.css.compiler.ast.GssParserCC.start(GssParserCC.java:2903)
        at com.google.common.css.compiler.ast.GssParserCC.parse(GssParserCC.java:174)
        ... 6 more


What version of the product are you using? On what operating system?

Latest from git, windows 7.

Please provide any additional information below.

option 
--allowed_non_standard_function calc() 
won't help.


```

Reported by `alexeykofficial` on 2013-10-11 09:49:30

**Comment by eunomie** [comment]
Is it always a bug?
On last `master` with attached `test.css`:

```
❯ java -jar build/closure-stylesheets.jar test.css
.test{width:calc(100% - 1px)}
```

**Comment by iflan** [comment]
It's likely that we've improved support for `calc` since this bug was submitted. Since you say it works, I'll close this out. Please re-open if that's not what you meant.

Thanks!
