### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by gg4u** [google/closure-stylesheets#74]
```java -jar closure-stylesheets.jar --help
Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/common/css/compiler/commandline/ClosureCommandLineCompiler : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:
```

runnning java:
java version "1.7.0_72"
Java(TM) SE Runtime Environment (build 1.7.0_72-b14)
Java HotSpot(TM) 64-Bit Server VM (build 24.72-b04, mixed mode)

**Comment by iflan** [comment]
Is this using the pre-compiled JAR or one that you built yourself?

**Comment by gg4u** [comment]
I compiled mylsef and installed following instructions (with maven?)

**Comment by iflan** [comment]
It looks like the JRE that you're using to run the JAR is older than the JDK you're using to build the JAR. From the error, you're compiling with [JDK 8](http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error).

Try this:
```
$ java -version
```
If it shows something like:
```
java version "1.7.0_55"
Java(TM) SE Runtime Environment (build 1.7.0_55-b13)
Java HotSpot(TM) 64-Bit Server VM (build 24.55-b03, mixed mode)
```
Then you're using JRE 7. You just have to change your path to use the `java` binary in your JDK.

**Comment by gg4u** [comment]
Oh @iflan , thank you. Yes using 1.7 , it clarified what error is.
