### ISSUE TITLE
CSS compiler broken with --output-source-map

### ISSUE THREAD

**Issue by jart** [google/closure-stylesheets#78]
The CSS compiler does not appear to work when I specify the `--output-source-map` flag. Here's what happens:

```
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:159)
        at com.google.common.css.compiler.passes.DefaultGssSourceMapGenerator.endSourceMapping(DefaultGssSourceMapGenerator.java:157)
        at com.google.common.css.compiler.passes.CodePrinter.leave(CodePrinter.java:103)
        at com.google.common.css.compiler.passes.UniformVisitor.leaveImportBlock(UniformVisitor.java:266)
        at com.google.common.css.compiler.ast.DefaultVisitController$RootVisitImportBlockState.doVisit(DefaultVisitController.java:387)
        at com.google.common.css.compiler.ast.DefaultVisitController.startVisit(DefaultVisitController.java:2028)
        at com.google.common.css.compiler.passes.PrettyPrinter.runPass(PrettyPrinter.java:614)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.parseAndPrint(DefaultCommandLineCompiler.java:144)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.compile(DefaultCommandLineCompiler.java:112)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.execute(DefaultCommandLineCompiler.java:157)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.executeJob(ClosureCommandLineCompiler.java:343)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:409)
```

On my classpath I have `com.google.closure-stylesheets:closure-stylesheets:20160212` and `com.google.javascript:closure-compiler:v20160208`.

**Comment by iflan** [comment]
I'm not sure that source map output actually works, even internally. The team that was working on it just sort of let it drop about half-way through and I'm not sure what the final state actually is.

**Comment by jart** [comment]
Out of curiosity, how committed is Google to the Closure Stylesheets compiler? Is it 20% only maintenance mode? I want to be able to recommend it as the best CSS compiler to use with Closure Tools. I want to be able to say that it will be continually supported by Google and be a safe choice for greenfield projects. Do you feel this is accurate? If not, what CSS compiler do you feel is the most recommendation worthy?

**Comment by Spunkie** [comment]
Has there been any further developments in fixing sourcemaps?

**Comment by iflan** [comment]
Yes. There are a few changes in review. I'll try to push them out next week.

**Comment by jart** [comment]
+1

**Comment by mikesamuel** [comment]
I believe this was addressed in https://github.com/google/closure-stylesheets/commit/713aff428d8ebff20935189a5c153c016a1f9dbf
