### ISSUE TITLE
Parse error: @media screen and (min-width:0\0)

### ISSUE THREAD

**Issue by mapx** [google/closure-stylesheets#81]
The hack in question: http://browserhacks.com/#hack-a60b03e301a67f76a5a22221c739dc64

```
com.google.common.css.compiler.ast.GssParserException: Parse error in /tmp/foundation.css at line 1,737 column 34:
  @media screen and (min-width: 0\0) {
                                 ^

        at com.google.common.css.compiler.ast.GssParserCC.parse(GssParserCC.java:227)
        at com.google.common.css.compiler.ast.GssParserCC.parse(GssParserCC.java:247)
        at com.google.common.css.compiler.ast.AbstractGssParser.parseInternal(AbstractGssParser.java:56)
        at com.google.common.css.compiler.ast.GssParser.parse(GssParser.java:46)
        at com.google.common.css.compiler.ast.GssParser.parse(GssParser.java:42)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.parseAndPrint(DefaultCommandLineCompiler.java:128)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.compile(DefaultCommandLineCompiler.java:112)
        at com.google.common.css.compiler.commandline.DefaultCommandLineCompiler.execute(DefaultCommandLineCompiler.java:157)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.executeJob(ClosureCommandLineCompiler.java:342)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:408)
Caused by: com.google.common.css.compiler.ast.ParseException: Encountered " <BAD_TOKEN> "\\ "" at line 1737, column 34.
Was expecting one of:
    "/" ...
    ")" ...
    <S> ...
    <IDENTIFIER> ...

        at com.google.common.css.compiler.ast.GssParserCC.generateParseException(GssParserCC.java:5083)
        at com.google.common.css.compiler.ast.GssParserCC.jj_consume_token(GssParserCC.java:4948)
        at com.google.common.css.compiler.ast.GssParserCC.term(GssParserCC.java:2005)
        at com.google.common.css.compiler.ast.GssParserCC.slash_term(GssParserCC.java:1758)
        at com.google.common.css.compiler.ast.GssParserCC.assign_term(GssParserCC.java:1709)
        at com.google.common.css.compiler.ast.GssParserCC.composite_term(GssParserCC.java:1659)
        at com.google.common.css.compiler.ast.GssParserCC.at_rule(GssParserCC.java:2921)
        at com.google.common.css.compiler.ast.GssParserCC.block(GssParserCC.java:3651)
        at com.google.common.css.compiler.ast.GssParserCC.start(GssParserCC.java:3744)
        at com.google.common.css.compiler.ast.GssParserCC.parse(GssParserCC.java:222)
        ... 9 more
```

**Comment by iflan** [comment]
The general rule is that we don't support hacks because the CSS compiler supports conditional compilation that can target individual browsers using `@if`. Please follow up if you believe that there should be an exception for this case.

**Comment by mapx** [comment]
The hack is written in [Foundation CSS framework](http://foundation.zurb.com/) v6.2.1 as:

https://github.com/zurb/foundation-sites/blob/d51418cbbfdbe9e4b06e5267fb3accd266d83571/scss/util/_mixins.scss#L121

It will be great if they can work together, or workaround has to be made :)
