### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by iSynth** [google/closure-stylesheets#94]
$ java -jar closure-stylesheets-21060712-SNAPSHOT-jar-with-dependencies.jar

```code
Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/base/Joiner
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler$Flags.<clinit>(ClosureCommandLineCompiler.java:71)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.parseArgs(ClosureCommandLineCompiler.java:364)
        at com.google.common.css.compiler.commandline.ClosureCommandLineCompiler.main(ClosureCommandLineCompiler.java:401)
Caused by: java.lang.ClassNotFoundException: com.google.common.base.Joiner
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 3 more
```

**Comment by iflan** [comment]
You are correct. I'm investigating. (And I guess I need to add a quick test of the assembled JAR to our release process, don't I?)

**Comment by iflan** [comment]
OK—this is because of the `<provided>` line here in `pom.xml`:

```xml
    <dependency>
      <groupId>com.google.guava</groupId>
      <artifactId>guava</artifactId>
      <version>${guava.version}</version>
      <scope>provided</scope> <!--- here --->
    </dependency>
```

If you delete that line and rebuild with `mvn clean compile assebly:single`, it should work. I'm assigning this to Mike because he made this change. I'll do another release when this is fixed. I'll also update our release checklist to make sure we actually test the runnable JAR.

**Comment by iSynth** [comment]
Thank you, now it works nicely.

**Comment by guoyanjun5** [comment]
# ## ###
